name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # 5. Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # 6. Publish application
      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 8. Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            pravij7/projectbackend:staging
            pravij7/projectbackend:${{ github.sha }}
          build-args: |
            JWT_KEY=${{ secrets.JWT_KEY }}
            ISSUER=${{ secrets.ISSUER }}
            AUDIENCE=${{ secrets.AUDIENCE }}
            REDIS_CONNECTIONSTRING=${{ secrets.REDIS_CONNECTIONSTRING }}
            REDIS_INSTANCENAME=${{ secrets.REDIS_INSTANCENAME }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_LOGIN=${{ secrets.EMAIL_LOGIN }}
            EMAIL_KEY=${{ secrets.EMAIL_KEY }}
            PROJECTID=${{ secrets.PROJECTID }}
            CREDENTIALSPATH=/app/firebase-service-account.json
            BACKBLAZESETTINGS_ACCESSKEY=${{ secrets.BACKBLAZESETTINGS_ACCESSKEY }}
            BACKBLAZESETTINGS_SECRETKEY=${{ secrets.BACKBLAZESETTINGS_SECRETKEY }}
            BACKBLAZESETTINGS_ENDPOINTURL=${{ secrets.BACKBLAZESETTINGS_ENDPOINTURL }}
            BACKBLAZESETTINGS_BUCKETNAME=${{ secrets.BACKBLAZESETTINGS_BUCKETNAME }}